-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.flyway_schema_history
(
    installed_rank integer NOT NULL,
    version character varying(50) COLLATE pg_catalog."default",
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    script character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    checksum integer,
    installed_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    installed_on timestamp without time zone NOT NULL DEFAULT now(),
    execution_time integer NOT NULL,
    success boolean NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE IF NOT EXISTS public.garcom
(
    id bigserial NOT NULL,
    cpf bigint,
    nome character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT garcom_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.item_pedido
(
    id bigserial NOT NULL,
    preco double precision,
    status boolean,
    idpedido bigint,
    idproduto bigint,
    CONSTRAINT item_pedido_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mesa
(
    id bigserial NOT NULL,
    num_mesa integer,
    status boolean,
    CONSTRAINT mesa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id bigserial NOT NULL,
    numpedido integer NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    idgarcom bigint,
    idmesa bigint,
    CONSTRAINT pedido_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.produto
(
    id bigserial NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default",
    preco double precision,
    CONSTRAINT produto_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.item_pedido
    ADD CONSTRAINT fk7w48nwkv01iyr22cje2ja9bnd FOREIGN KEY (idproduto)
    REFERENCES public.produto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item_pedido
    ADD CONSTRAINT fkj6m352d4dwsig3xrho17c4jd0 FOREIGN KEY (idpedido)
    REFERENCES public.pedido (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT fka5wgeshv70jbat7u2o1c2me1k FOREIGN KEY (idgarcom)
    REFERENCES public.garcom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT fkcsw6stxyrcrt1a7lmbvug145h FOREIGN KEY (idmesa)
    REFERENCES public.mesa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;